---
title: "About"
---

Welcome! I created this simple site as a mini-portfolio for my job search (social science research/analyst positions) that concluded in the summer of 2022. Now that I am [happily employed](https://raymarshallcenter.org/2022/09/09/david-mccoy-ma/), I am leaving this here in case the example or the worked solutions might be useful for others. 

For those on the fence about investing the time to make some kind of portfolio (not a standard practice in the social sciences), I can attest that I saw an immediate shift in results for my job search after I took a week off from applying for jobs to create this. Over two months, I had applied to approximately 20 jobs before making this site and had been invited to only one interview. I completed this site between the invitation and the date of the first interview, and it was clear during the interview that it had made an impression. In the following two weeks, after adding a link to the site on my resume, I was invited to two more interviews and was lucky enough to recieve two offers (I declined the third interview, as I was happy with the second offer). All that is to say that this mini-portfolio was certainly worth the time and effort for me.

You can find the code used to create this site and most of the data (some files are too large) for replicating the analyses at [my GitHub page](https://github.com/DavidRMcCoy/DavidRMcCoy.io).


## Previews of my Three Code Examples

These three analyses are a mix of pet projects and more developed analyses. They demonstrate that I am comfortable working creatively and competently with data emanating from a wide range of topics and sources, as well as designing creative solutions to answering research questions. The first example focuses most on wrangling and visualizing complex data related to race/ethnicity, poverty, and education outcomes in Texas public schools. The second is most focused on research design and testing hypotheses related to gender equity in Brazilian elections and representation of women's interests in the legislature. The third example is focused on wrangling and joining large, complex data sets, data transformations, and creating niche visualizations of COVID-19 data and Google Community Mobility data. 
```{r, results = "asis", warning = FALSE, message = FALSE, echo = FALSE}
image_link <- function(image,url,...){
  htmltools::a(
    href=url,
    htmltools::img(src=image,...)
    )
}

image_link("ed.png", "https://davidrmccoy.github.io/DavidRMcCoy.io/TX_ed.html", width="300px")
image_link("gen.png", "https://davidrmccoy.github.io/DavidRMcCoy.io/gender_rep.html", width="200px")
image_link("waves_1_2_mob_death.gif", "https://davidrmccoy.github.io/DavidRMcCoy.io/covid_vis.html", width="200px")

```

<div align="right">**Note: Some of these visualizations are large and might not appear as intended when viewed on a mobile device.**</div>  

